# Site settings
title: Louis Cho Docs
email: your-email@domain.com
author: Louis Cho
description: > 
  Welcome to Louis Cho's GitHub Pages. Here you can find my study notes, projects, and technical writings.

# Important: baseurl과 url을 맞춰야 함
baseurl: "" # 루트 도메인이라면 빈 값 ("") 
url: "https://louis-cho.github.io" # 깃허브 페이지 주소

# Repository Settings
repo: "https://github.com/louis-cho/louis-cho.github.io"
github_user: "louis-cho"
github_repo: "louis-cho.github.io"
github_branch: "main"

# (선택) 소셜 미디어
# twitter: your_twitter_id
# linkedin: your_linkedin_id

# Versions (필요없으면 생략 가능)
version_params:
  version_menu: "Release"
  version_dir: Archive
  tocversion_dir: versions
  versioning: true          # 버전 관리 안하면 false
  latest: v1.1
  allow_search: true
  search_versions:
    - v1.1
    - v1.0
    - v0.1
  versions:
    - v1.1
    - v1.0
    - v0.1

# Footer 옵션
feedback: true
# privacy: https://your-privacy-policy-url.com

# Analytics
# google-analytics: UA-XXXXXXXXXX

# Logo, 색상 설정
# logo: "assets/img/logo.png" # (필요시 이미지 경로 추가)
logo_pixels: 34
color: "#30638e" # 기본 메인 색
accentColor: red
themeColor: red
fixedNav: 'true'

# Build settings
markdown: kramdown
permalink: /:year/:title/
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: post
